databases:
  - name: n8n-database
    plan: free
    region: frankfurt

services:
  - type: web
    name: n8n-service
    env: docker
    repo: https://github.com/n8n-io/n8n
    branch: master
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    envVars:
      # --- Database config ---
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-database
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-database
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-database
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-database
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-database
          property: password

      # --- Security ---
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "anicet22.aps2a@gmail.com"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "N8N-deploy"

      # --- Host config ---
      - key: N8N_HOST
        value: n8n-deploy-5io2.onrender.com
      - key: N8N_PORT
        value: "443"
      - key: N8N_PROTOCOL
        value: https

