services:
  - type: web
    name: n8n
    env: docker
    region: frankfurt
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: YOUR_SUPABASE_HOST
      - key: DB_POSTGRESDB_DATABASE
        value: YOUR_SUPABASE_DATABASE
      - key: DB_POSTGRESDB_PORT
        value: YOUR_SUPABASE_PORT
      - key: DB_POSTGRESDB_USER
        value: YOUR_SUPABASE_USER
      - key: DB_POSTGRESDB_PASSWORD
        value: YOUR_SUPABASE_PASSWORD
      - key: DB_POSTGRESDB_SSLMODE
        value: require
      - key: PORT
        value: 5678
      - key: N8N_LOG_LEVEL
        value: info
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: TZ
        value: Europe/Paris
      - key: N8N_DEFAULT_LOCALE
        value: fr
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
     

